# Dependencies
gems:             [jekyll-paginate, jekyll-seo-tag]
markdown:         kramdown
highlighter:      rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Excer[ts
excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:            'Mindful Things'
tagline:          'Blog'
description:      'Musings on tech, books, and other subjects too variable to enumerate. Written by <a href="https://twitter.com/vijayiyengar" target="_blank">@vijayiyengar</a>.'
url:              http://ranic.github.io
baseurl:          /

author:
  name:           'Vijay Jayaram'
  url:            https://www.linkedin.com/vijay4

paginate:         5

# Custom vars
version:          2.1.0

social:
  github:
    repo:         'https://github.com/ranic'
  linkedin:       'https://linkedin.com/in/vijay4'
